when@dev:
    web_profiler:
        toolbar: true
        intercept_redirects: false

    framework:
        profiler:
            only_exceptions: false
            collect: true
            collect_serializer_data: true

when@test:
    framework:
        profiler: { collect: false }
